### ISSUE TITLE
when I published neon,Unable generated exe file

### ISSUE THREAD

**Issue by steel1985** [neo-project/neo-compiler#154]
Yesterday I wanted to update neon,When I published neon,Unable generated exe file.

![微信图片_20190508111827](https://user-images.githubusercontent.com/4490002/57346936-1f391580-7183-11e9-910a-672b06d58ee2.png)

**Comment by steven1227** [comment]
Had the same problem.... it looks like the problem occurs after this [commit](https://github.com/neo-project/neo-compiler/commit/c73dba54995bf32290cbdb3409d875feee30f294)

**Comment by steven1227** [comment]
@shargon Hi Sharon. In the image from @steel1985 , there is no error actually and the problem is we can not find the exe. The problem I guess is the visual studio 2019 and the new version of dotnet core. My env in my new laptop is visual studio 2019 with new dotnetcore 2.2.203 which is not compatible with visual studio 2018 (there is a [compatible version](https://dotnet.microsoft.com/download)) and got the same problem that can not generate exe.

**Comment by lightszero** [comment]
@steven1227 yes,I found that in many computer vistual studio can not publish.
bu in cmd line it is good alltime.

you can change to neon project path in console,and type

> dotnet publish -f netcoreapp2.0 -r win7-x64

 to publish it

> D:\git\neo\neo-compiler\neon>dotnet publish -f netcoreapp2.0 -r win7-x64

**Comment by shargon** [comment]
Please @steven1227 reopen the issue if your problem persist

**Comment by erikzhang** [comment]
I think it's a compatibility issue with Visual Studio 2019.
